# References {-}

<div id="refs"></div>


Donn, M., Bekele, E., Wu, H., Prommer, H., Furness, A., Woodbury, R., Rayner, J., & Davis, G. (2025). Baseline assessment of groundwater/surface water nitrogen flux into Cockburn Sound – Final Report. [WAMSI Westport Marine Science Program, Project 3.3.4b](https://wamsi.org.au/research_themes/water-and-sediment-quality/). 

Greenwood, J., Keesing, J.K., Donn, M.J., & McFarlane, D.J. (2016). Nitrogen Budget for Cockburn Sound, Western Australia. Report to the Cockburn Sound Management Council and the Western Australian Department of Water. CSIRO, Australia.

Loveless, A., & Oldham, C. (2010). Natural attenuation of nitrogen in groundwater discharging through a sandy beach. Biogeochemistry, 98, 75–87. https://doi.org/10.1007/S10533-009-9377-X

Loveless, A., Oldham, C., & Hancock, G. (2008). Radium isotopes reveal seasonal groundwater inputs to Cockburn Sound, a marine embayment in Western Australia. Journal of Hydrology, 351, 203–217. https://doi.org/10.1016/J.JHYDROL.2007.12.010


Boudreau, B. P., (1996), A method-of-lines code for carbon and nutrient diagenesis in aquatic sediments, 22, 5, 479-496.

Dalseno, T. C., Greenwood, J., Keesing, J. K. and Feng, M., (2024), Seasonal deoxygenation in a shallow coastal embayment: The role of stratification and implications for water-quality monitoring, 77, 103738.

Donn, M., Bekele E., Tapsuwan, S. and McFarlane, D. (2015) Chapter 10 – Managed Aquifer Recharge Scenarios. In: Recycled water for heavy industry and preventing sea water intrusion. McFarlane D.J. (ed.) A report to the Australian Water Recycling Centre of Excellence, Government and industry partners from the CSIRO Land and Water Flagship

Donn, M., Bekele, E., Wu, H., Prommer, H., Furness, A., Woodbury, R., Rayner, J., Davis, G. (2025) Project 3.3: Baseline assessment of groundwater/surface water nitrogen flux into Cockburn Sound - Final report

Eyre, B., van Haastregt, B., Eyre, J., Yeo, J. (2025). Cockburn Sound Benthic Biogeochemistry Final Report. Prepared for the WAMSI Westport Marine Science Program. Western Australian Marine Science Institution, Perth, Western Australia. 38 pp

Greenwood, J., (2016), Nitrogen budget for Cockburn Sound, Western Australia, Perth, Western Australia: Report to the Cockburn Sound Management Council and the Western Australian Department of Water, CSIRO: Perth. https://www. water. wa. gov. au/__data/assets/pdf_file/0019 …,

Jørgensen, B. B., Wenzhöfer, F., Egger, M. and Glud, R. N., (2022), Sediment oxygen consumption: Role in the global marine carbon cycle, 228, 103987.

Koch, M. S., Benz, R. E. and Rudnick, D. T., (2001), Solid-phase phosphorus pools in highly organic carbonate sediments of northeastern Florida Bay, 52, 2, 279-291.

Lord, D. A., (2001), The State of Cockburn Sound: A Pressure-State-Response Report, DA Lord & Associates,

Mackin, J. E. and Aller, R. C., (1984), Ammonium adsorption in marine sediments 1, 29, 2, 250-257.

Middelburg, J. J., (2019), Carbon processing at the seafloor, Springer, 57-75.

Van Cappellen, P. and Wang, Y., (1995), Metal cycling in surface sediments: modeling the interplay of transport and reaction, Routledge, 21-64.

Van Cappellen, P. and Wang, Y., (1996), Cycling of iron and manganese in surface sediments; a general theory for the coupled transport and reaction of carbon, oxygen, nitrogen, sulfur, iron, and manganese, 296, 3, 197-243.

Wijsman, J. W. M., Herman, P. M. J., Middelburg, J. J. and Soetaert, K., (2002), A model for early diagenetic processes in sediments of the continental shelf of the Black Sea, 54, 3, 403-421.

Zhou, C., Liu, D., Keesing, J., Zhao, N., Serrano, O., Masqué, P., Yuan, Z., Jia, Y. and Wang, Y., (2024), Microalgal assemblages response to water quality remediation in coastal waters of Perth, Australia, 351, 124017.
